import type { NextPage } from "next";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { Header } from "../components/Header";
import { Nav } from "../components/Nav";
import { Results } from "../components/Results";

import { getRequest } from "../utils/requests";

interface HomeProps {
  results: any;
}

const Home: NextPage<HomeProps> = (props: HomeProps) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Nav />

      <Results results={props.results} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const genre = context.query.genre as string;

  const request = await fetch(
    `https://api.themoviedb.org/3${getRequest(genre).url}`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    } as HomeProps,
  };
};

export default Home;
